import type { Portfolio } from './types';

export const demoPortfolio = {
  studioName: 'Northline Portrait Studio',
  location: 'Indianapolis, Indiana',
  email: 'hello@northline.example',
  conceptNotice: 'Fictional studio and concept content created for demonstration purposes.',
  home: {
    eyebrow: 'Portraits with presence',
    headline: 'Honest photographs for the work and lives you are building.',
    introduction:
      'Northline creates quietly cinematic portraits of artists, founders, and families throughout Indianapolis and beyond.',
    biography:
      'Led by fictional photographer Mara Ellis, the studio pairs patient direction with natural light and a documentary eye. Sessions are unhurried, collaborative, and shaped around the details that make a person feel unmistakably themselves.',
    announcement: 'Now booking autumn portrait sessions in Indianapolis and Chicago.',
    contactLabel: 'Begin a conversation',
    featuredGallerySlugs: ['artists-in-quiet-rooms', 'after-dark', 'makers-at-work'],
  },
  galleries: [
    {
      id: 'gallery-artists',
      slug: 'artists-in-quiet-rooms',
      title: 'Artists in Quiet Rooms',
      category: 'Editorial portraiture',
      description:
        'A study of painters, musicians, and writers in the private rooms where their work first takes shape.',
      cover: {
        id: 'artists-cover',
        src: '/images/northline/artist-window.webp',
        alt: 'Painter seated beside a tall studio window with folded hands',
        caption: 'A quiet morning in the north-facing studio.',
        width: 1800,
        height: 2400,
      },
      images: [
        {
          id: 'artists-01',
          src: '/images/northline/artist-red-room.webp',
          alt: 'Artist seated in a red room beside a canvas',
          caption: 'Between firings, surrounded by the marks of the process.',
          width: 1600,
          height: 2000,
        },
        {
          id: 'artists-02',
          src: '/images/northline/artist-profile.webp',
          alt: 'Artist in profile against a softly lit studio wall',
          caption: null,
          width: 1600,
          height: 2000,
        },
        {
          id: 'artists-03',
          src: '/images/northline/artist-window.webp',
          alt: 'Painter seated beside a tall studio window with folded hands',
          caption: 'A pause before rehearsal.',
          width: 1800,
          height: 2400,
        },
        {
          id: 'artists-04',
          src: '/images/northline/artist-red-room.webp',
          alt: 'Artist seated in a red room beside a canvas',
          caption: null,
          width: 1600,
          height: 2000,
        },
      ],
      publishedAt: '2025-09-18T14:00:00.000Z',
    },
    {
      id: 'gallery-after-dark',
      slug: 'after-dark',
      title: 'After Dark',
      category: 'Night portraits',
      description:
        'Neon, rain, and late-night storefronts become a shifting stage for portraits made across the city.',
      cover: {
        id: 'after-dark-cover',
        src: '/images/northline/night-neon.webp',
        alt: 'Musician standing beneath blue neon on a rain-dark street',
        caption: 'Washington Street, just after the rain.',
        width: 1800,
        height: 2400,
      },
      images: [
        {
          id: 'after-dark-01',
          src: '/images/northline/night-theater.webp',
          alt: 'Performer waiting beneath a glowing theater marquee',
          caption: 'The last show had already let out.',
          width: 1800,
          height: 1200,
        },
        {
          id: 'after-dark-02',
          src: '/images/northline/night-car.webp',
          alt: 'Portrait subject leaning against a car under city lights',
          caption: null,
          width: 1800,
          height: 1200,
        },
        {
          id: 'after-dark-03',
          src: '/images/northline/night-neon.webp',
          alt: 'Musician standing beneath blue neon on a rain-dark street',
          caption: 'A borrowed pool of light on Mass Ave.',
          width: 1800,
          height: 2400,
        },
        {
          id: 'after-dark-04',
          src: '/images/northline/night-theater.webp',
          alt: 'Performer waiting beneath a glowing theater marquee',
          caption: null,
          width: 1800,
          height: 1200,
        },
      ],
      publishedAt: '2025-11-07T14:00:00.000Z',
    },
    {
      id: 'gallery-makers',
      slug: 'makers-at-work',
      title: 'Makers at Work',
      category: 'Brand stories',
      description:
        'Environmental portraits of independent makers, photographed among the tools, materials, and rituals of their craft.',
      cover: {
        id: 'makers-cover',
        src: '/images/northline/maker-ceramics.webp',
        alt: 'Ceramic artist shaping clay at a sunlit workbench',
        caption: 'The workshop before the first cut of the day.',
        width: 1800,
        height: 2400,
      },
      images: [
        {
          id: 'makers-01',
          src: '/images/northline/maker-florist.webp',
          alt: 'Floral designer arranging stems at a worktable',
          caption: null,
          width: 1600,
          height: 2000,
        },
        {
          id: 'makers-02',
          src: '/images/northline/maker-tailor.webp',
          alt: 'Tailor measuring dark fabric at a cutting table',
          caption: 'Finishing the edge by hand.',
          width: 1600,
          height: 2000,
        },
        {
          id: 'makers-03',
          src: '/images/northline/studio-hands.webp',
          alt: 'Maker hands guiding material across a studio worktable',
          caption: null,
          width: 1800,
          height: 1200,
        },
        {
          id: 'makers-04',
          src: '/images/northline/maker-ceramics.webp',
          alt: 'Ceramic artist shaping clay at a sunlit workbench',
          caption: 'Small gestures, repeated until they become instinct.',
          width: 1800,
          height: 2400,
        },
      ],
      publishedAt: '2026-01-22T14:00:00.000Z',
    },
  ],
  posts: [
    {
      id: 'post-light-before-session',
      slug: 'the-light-before-the-session',
      title: 'The Light Before the Session',
      excerpt: 'Why the first quiet minutes in a space often decide the visual language of a portrait.',
      body: [
        'Before a camera leaves the bag, I watch the room. Light moves across walls, catches the edge of a chair, and reveals where someone might naturally pause. Those observations become the beginning of the session.',
        'Good portrait light does not need to announce itself. More often, it is the soft reflection from a pale floor or a narrow window that lets a face feel dimensional without becoming theatrical.',
        'Arriving early gives us room to notice those details together. By the time we begin, the location already feels less like a set and more like a place where an honest moment can happen.',
      ],
      cover: {
        id: 'post-light-cover',
        src: '/images/northline/studio-contact-sheet.webp',
        alt: 'Photographic contact sheet arranged on a studio light table',
        caption: 'The studio, twenty minutes before a session.',
        width: 1800,
        height: 1200,
      },
      relatedGallerySlug: 'artists-in-quiet-rooms',
      publishedAt: '2026-02-12T14:00:00.000Z',
    },
    {
      id: 'post-portrait-wardrobe',
      slug: 'building-a-portrait-wardrobe',
      title: 'Building a Portrait Wardrobe',
      excerpt: 'A practical approach to clothing that supports a portrait without making it feel overly styled.',
      body: [
        'The most useful wardrobe begins with clothes you already trust. A familiar jacket, a shirt with movement, or a pair of well-worn boots often carries more character than something purchased only for the camera.',
        'Start with a restrained range of colors, then add texture through wool, linen, denim, or silk. These materials respond beautifully to directional light and give the frame depth without competing for attention.',
        'Bring a few options and leave room to improvise. We will choose pieces according to the location, the light, and how you want the photographs to feel rather than following a rigid formula.',
      ],
      cover: {
        id: 'post-wardrobe-cover',
        src: '/images/northline/maker-tailor.webp',
        alt: 'Tailor measuring dark fabric at a cutting table',
        caption: null,
        width: 1600,
        height: 2000,
      },
      relatedGallerySlug: 'after-dark',
      publishedAt: '2026-03-05T14:00:00.000Z',
    },
    {
      id: 'post-why-print',
      slug: 'why-we-print-photographs',
      title: 'Why We Print Photographs',
      excerpt: 'A portrait changes when it leaves the screen and becomes an object you can live with.',
      body: [
        'Screens encourage us to move quickly. A print asks for a different kind of attention: its scale is fixed, its surface responds to the room, and it stays present after the device has gone dark.',
        'We make proof prints throughout the editing process because paper reveals relationships that a backlit display can hide. Shadow detail, skin tone, and subtle color all become easier to judge when the image is held in the hand.',
        'The final print is not an extra version of the photograph. It is the photograph taking its intended form—something tangible enough to pass from one person to another and durable enough to gather meaning over time.',
      ],
      cover: {
        id: 'post-print-cover',
        src: '/images/northline/studio-print.webp',
        alt: 'Archival portrait prints spread across a dark wooden table',
        caption: 'Sequencing a set of small exhibition prints.',
        width: 1800,
        height: 1200,
      },
      relatedGallerySlug: null,
      publishedAt: '2026-04-16T14:00:00.000Z',
    },
  ],
  packages: [
    {
      id: 'package-portrait',
      name: 'The Portrait Session',
      startingPrice: 'From $850',
      description: 'A considered session for one person, built around a single location and a clear visual story.',
      features: ['Planning consultation', 'Up to two hours of photography', '25 finished photographs', 'Five archival prints'],
      ctaLabel: 'Ask about this package',
    },
    {
      id: 'package-story',
      name: 'The Brand Story',
      startingPrice: 'From $1,600',
      description: 'An image library for independent studios and small teams who want their work to feel human.',
      features: ['Creative direction', 'Half-day coverage', '60 finished photographs', 'Personal and commercial web use'],
      ctaLabel: 'Ask about this package',
    },
    {
      id: 'package-archive',
      name: 'The Family Archive',
      startingPrice: 'From $1,250',
      description: 'Unhurried family portraiture designed to become part of the visual history of a home.',
      features: ['Pre-session planning', 'Up to ninety minutes of photography', '40 finished photographs', 'Linen print folio'],
      ctaLabel: 'Ask about this package',
    },
  ],
} satisfies Portfolio;
