// Presentation only. Exact demo hosts; never select a theme by a customer name.
const hosts = new Map([
  ['demo.leonsites.org', 'sports'], ['demo-test.leonsites.org', 'sports'],
  ['vow-and-light.leonsites.org', 'wedding'], ['vow-and-light-test.leonsites.org', 'wedding'],
]);
export function demoDesignFor(hostname, pathname) {
  const kind = hosts.get(hostname.toLowerCase());
  return kind && /^\/(?:work(?:\/[^/]+)?|packages|contact)?\/?$/.test(pathname) ? kind : null;
}
const esc = value => String(value ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const safeImage = value => {
  const s = String(value ?? '');
  return (s.startsWith('/') && !s.startsWith('//')) || /^https:\/\//.test(s) ? esc(s) : '';
};
const link = gallery => `/work/${encodeURIComponent(gallery.slug)}`;
const picture = (image, cls = '', eager = false) => image ? `<img class="${cls}" src="${safeImage(image.src)}" alt="${esc(image.alt)}" width="${Number(image.width) || 1600}" height="${Number(image.height) || 1200}" loading="${eager ? 'eager' : 'lazy'}" ${eager ? 'fetchpriority="high"' : ''} decoding="async">` : '';
const arrow = '';
/** Render only already-authorized public portfolio data; no API calls or writes. */
export function renderDemoDocument({kind, portfolio: p, pathname, canonicalOrigin}) {
  const wedding = kind === 'wedding';
  const path = pathname.replace(/\/$/, '') || '/';
  const galleries = p.galleries || [];
  const allImages = galleries.flatMap(g => g.images);
  const hero = wedding ? allImages.find(i => i.src.includes('wedding-window')) || allImages[0] : allImages.find(i => i.src.includes('football-player')) || allImages[0];
  const second = wedding ? allImages.find(i => i.src.includes('wedding-window')) || allImages[1] : allImages.find(i => i.src.includes('football-field')) || allImages[1];
  const name = p.studioName;
  const wordmark = wedding ? 'Vow <i>&</i> Light' : 'NORTHLINE<span>Sports photography</span>';
  const cta = wedding ? 'Ask about your wedding' : 'Ask about coverage';
  const realContact = `https://leonsites.org/contact?demo=${wedding ? 'vow-and-light' : 'northline-sports'}`;
  const nav = [['/work', 'The work'], ['/packages', wedding ? 'The experience' : 'Coverage'], ['/contact', wedding ? 'Inquire' : 'Get in touch']];
  const cards = galleries.map((g, i) => `<a class="project project-${i}" href="${link(g)}"><div class="project-image">${picture(!wedding ? g.images.find(img=>img.src.includes('basketball-grayscale')) || g.cover : g.cover)}<span class="image-action">View gallery</span></div><div class="project-caption"><h3>${esc(g.title)}</h3><span>${esc(g.category)}</span></div></a>`).join('');
  const closing = `<section class="closing"><h2>${wedding ? 'Planning your wedding?' : 'Need a photographer?'}</h2><p>${wedding ? 'Tell us the date, the place, and a little about the two of you.' : 'Send the date, the sport, and the kind of coverage you need.'}</p><a class="button" href="/contact">${cta}</a></section>`;
  let content = '', title = name;
  if (path === '/') {
    const alternate = wedding ? allImages.find(i=>i.src.includes('wedding-dance')) || allImages[1] : allImages.find(i=>i.src.includes('track-runner')) || allImages[1];
    content = wedding ? `<section class="album-hero"><figure class="album-lead">${picture(hero, '', true)}<figcaption>Wedding photography by Vow &amp; Light</figcaption></figure><div class="album-side"><div class="album-intro"><h1>A day with your favourite people.</h1><p>Wedding photography with space to enjoy being there.</p><a class="text-link" href="/work">Explore the photographs</a></div><figure class="album-secondary">${picture(alternate)}<figcaption>The moments in between.</figcaption></figure></div></section>` : `<section class="field-hero"><div class="field-intro"><h1>Game days,<br>up close.</h1><p>Sports photography for teams, athletes, and the people cheering them on.</p><a class="button" href="/work">Browse the work</a><p class="field-location">${esc(p.location)}</p></div><figure class="field-photo">${picture(hero, '', true)}<figcaption>Northline Sports / On the sidelines</figcaption></figure></section>`;
    const album = wedding && galleries[0] ? `<a class="album-spread" href="${link(galleries[0])}" aria-label="Open the wedding photograph collection">${allImages.slice(0,3).map(img=>`<figure>${picture(img)}</figure>`).join('')}<span>View the collection</span></a>` : `<div class="project-grid">${cards}</div>`;
    content += `<section class="selected section-pad"><div class="section-heading"><h2>${wedding ? 'A few favourites.' : 'The work'}</h2><a class="text-link" href="/work">All galleries</a></div>${album}</section><section class="approach section-pad"><div class="approach-image">${picture(wedding ? allImages.find(i=>i.src.includes('wedding-courthouse')) || second : second)}</div><div class="approach-copy"><h2>${wedding ? 'Enjoy the day.<br>We’ll take the photographs.' : 'One game or<br>the whole season.'}</h2><p>${wedding ? 'Time with your family. A few portraits together. Plenty of room for everything that happens in between.' : 'Game coverage, athlete sessions, and season-long photography. Find the coverage that fits your team.'}</p><a class="text-link" href="/packages">${wedding ? 'Wedding photography details' : 'See coverage options'}</a></div></section>`;
  } else if (path === '/work') {
    title = `The work — ${name}`;
    content = `<header class="page-heading section-pad"><h1>${wedding ? 'Wedding photographs' : 'The work'}</h1><p>${wedding ? 'A collection of portraits, celebrations, and quieter moments.' : 'Football, basketball, and track. Open a gallery to see the photographs.'}</p></header><section class="archive section-pad" aria-label="Photography galleries"><div class="project-grid">${cards}</div></section>${closing}`;
  } else if (path.startsWith('/work/')) {
    const slug = decodeURIComponent(path.slice(6));
    const g = galleries.find(g => g.slug === slug);
    title = `${g?.title || 'Gallery not found'} — ${name}`;
    if (g) {
      const next = galleries[(galleries.indexOf(g) + 1) % galleries.length];
      content = `<header class="gallery-heading section-pad"><a class="text-link" href="/work">← All work</a><p class="eyebrow">${esc(g.category)}</p><h1>${esc(g.title)}</h1><div class="gallery-meta"><p>${esc(g.description)}</p><span>${String(g.images.length).padStart(2, '0')} photographs / Click to explore</span></div></header><section class="gallery-images section-pad" aria-label="${esc(g.title)} photographs">${g.images.map((img,i) => `<button class="gallery-photo photo-${i}" type="button" data-lightbox data-caption="${esc(img.alt)}" aria-label="Enlarge photograph ${i+1}: ${esc(img.alt)}">${picture(img, '', i===0)}<span aria-hidden="true">${String(i+1).padStart(2,'0')} / Expand ↗</span></button>`).join('')}</section><nav class="next-gallery section-pad" aria-label="Gallery navigation"><span>${galleries.length > 1 ? 'Next gallery' : 'Back to the collection'}</span><a href="${galleries.length > 1 ? link(next) : '/work'}">${galleries.length > 1 ? esc(next.title) : 'All stories'} ${arrow}</a></nav>`;
    } else content = '<section class="page-heading section-pad"><p class="eyebrow">404</p><h1>Out of frame.</h1><a class="button" href="/work">Back to the work ↗</a></section>';
  } else if (path === '/packages') {
    title = `${wedding ? 'The experience' : 'Coverage'} — ${name}`;
    content = `<header class="service-heading section-pad"><div><p class="eyebrow">${wedding ? 'The experience' : 'Coverage, your way'}</p><h1>${wedding ? 'Wedding photography' : 'Photography coverage'}</h1><p>${wedding ? 'Thoughtful photography. Space to be yourselves. A story that feels like you.' : 'One game. A full season. A story built around your team.'}</p></div>${picture(second, '', true)}</header><section class="services section-pad" aria-labelledby="services-title"><div class="section-heading"><h2 id="services-title">Coverage options</h2><p class="demo-note">Sample photography packages for this demo.</p></div>${p.packages.map(s => `<article class="service"><div><h3>${esc(s.name)}</h3><p>${esc(s.description)}</p><ul>${s.features.map(f => `<li>${esc(f)}</li>`).join('')}</ul></div><div class="service-action"><p>${esc(s.startingPrice)}</p><a class="button" href="/contact?package=${encodeURIComponent(s.id)}">${wedding ? 'Tell us more' : 'Plan your coverage'} ${arrow}</a></div></article>`).join('')}</section>${closing}`;
  } else {
    title = `Inquire — ${name}`;
    content = `<section class="contact-layout section-pad"><div class="contact-copy"><p class="eyebrow">${wedding ? 'Wedding inquiries' : 'Sports photography inquiries'}</p><h1>${wedding ? 'Tell us about<br>your wedding.' : 'Book your<br>coverage.'}</h1>${picture(second)}<p class="demo-note">This is a demo studio. Try the inquiry preview—nothing is sent or stored. Want this website for your photography? <a href="${realContact}">Talk to Leon ↗</a></p></div><div class="contact-form-panel"><h2>${wedding ? 'Your details' : 'Your details'}</h2><p>Explore how an inquiry could feel on your own website.</p><form data-demo-inquiry method="dialog"><label>Your name<input name="name" required minlength="2" maxlength="120" autocomplete="off" placeholder="Alex Morgan"></label><label>Email address<input name="email" type="email" required maxlength="254" autocomplete="off" placeholder="you@example.com"></label><div class="form-row"><label>${wedding ? 'Your date' : 'Event date'}<input type="date" name="date" required></label><label>Location<input name="location" maxlength="160" placeholder="City or venue" required></label></div><label>${wedding ? 'What are you planning?' : 'What do you have in mind?'}<select name="package"><option value="">Let’s figure it out</option>${p.packages.map(s => `<option value="${esc(s.id)}">${esc(s.name)}</option>`).join('')}</select></label><label>A few more details<textarea name="message" rows="4" maxlength="3000" required minlength="10" placeholder="Tell us about the people, the plans, and the moments that matter."></textarea></label><button class="button" type="submit" disabled>Preview inquiry ${arrow}</button><p class="demo-note">Demo only · No email is sent · No booking is made</p><div class="form-result" role="status" tabindex="-1" hidden><h3>That’s how your inquiry could start.</h3><p>This was a preview. Your details haven’t been sent or saved.</p><a class="text-link" href="${realContact}">Get an inquiry page for your own site ${arrow}</a></div><noscript><p>This preview needs JavaScript. You can still <a href="${realContact}">contact Leon about your website</a>.</p></noscript></form></div></section>`;
  }
  return `<!doctype html><html lang="en" class="demo-${kind}"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>${esc(title)}</title><meta name="description" content="${esc(wedding ? 'Vow & Light: a cinematic wedding photography website concept by Sites by Leon.' : 'Northline Sports: an editorial sports photography website concept by Sites by Leon.')}"><meta property="og:title" content="${esc(title)}"><meta property="og:type" content="website"><meta property="og:image" content="${hero ? esc(new URL(hero.src, canonicalOrigin).href) : ''}"><link rel="canonical" href="${esc(new URL(path, canonicalOrigin).href)}"><meta name="theme-color" content="${wedding ? '#ffffff' : '#f7f9fc'}"><link rel="icon" href="/favicon.svg"><link rel="stylesheet" href="/demo-assets/demo-v4.css"><script src="/demo-assets/demo-v4.js" defer></script></head><body><a class="skip" href="#main">Skip to content</a><aside class="demo-bar" aria-label="Website demo"><span>A Sites by Leon demo</span><a href="${realContact}">Get a site like this ${arrow}</a></aside><header class="demo-header"><a class="brand" href="/" aria-label="${esc(name)}, home">${wordmark}</a><nav aria-label="Main navigation">${nav.map(([url,label]) => `<a href="${url}" ${path===url || url==='/work' && path.startsWith('/work/') ? 'aria-current="page"' : ''}>${label}</a>`).join('')}</nav></header><main id="main">${content}</main><footer class="demo-footer"><a class="brand" href="/">${wordmark}</a><nav aria-label="Footer navigation">${nav.map(([url,label]) => `<a href="${url}">${label}</a>`).join('')}</nav><div class="footer-bottom"><p>Photography website demo. No bookings are taken.</p><a href="${realContact}">Built by Sites by Leon ${arrow}</a></div></footer><dialog class="lightbox" aria-label="Photograph viewer"><div class="lightbox-toolbar"><p data-lightbox-counter></p><button data-lightbox-close aria-label="Close photograph viewer">Close ×</button></div><img alt=""><div class="lightbox-bottom"><button data-lightbox-prev aria-label="Previous photograph">←</button><p data-lightbox-caption></p><button data-lightbox-next aria-label="Next photograph">→</button></div></dialog></body></html>`;
}
